sudo: true

language: go

before_install:
  - sudo apt-get install -y bsdiff

install:
  - mkdir -p $GOPATH/bin
  - mkdir -p $GOPATH/pkg
  - mkdir -p $GOPATH/src
  - curl https://glide.sh/get | sh
  - make vendor

script:
  - go test -v ./...
